enyo.depends(
	"$lib/onyx",
	"$lib/layout/Fitable/Fitable.css",
	"$lib/layout/Fitable/Fitable.js",
	"maps",
	"source/mockdata.js",
	"source/CurrentLocation.js",
	"source/IconButton.js",
	"source/RadioIconButton.js",
	"source/LabeledItem.js",
	"source/BookmarkList.js",
	"source/Pullout.js",
	"source/Infobox.js",
	"source/MapsApp.css",
	"source/MapsApp.js"
);