enyo.depends(
	"$lib/onyx",
	"$lib/layout/fittable",
	"maps",
	"source/mockdata.js",
	"source/CurrentLocation.js",
	"source/LabeledItem.js",
	"source/BookmarkList.js",
	"source/Pullout.js",
	"source/Infobox.js",
	"source/MapsApp.css",
	"source/MapsApp.js"
);